### ISSUE TITLE
Code review 1

### ISSUE THREAD

**Issue by FrancoRosa** [HADDADSOHAIB/microtube#2]
Test

**Comment by idgm5** [comment]
https://i.imgur.com/Ph15N8f.png

I think you can make the navigation bar more friendly for mobile or small screens by creating a Media query.

A good example could be something like: 

```
@media (min-width: 900px) {
  .fa-upload {
      display: none;
      }
  }
```

https://www.w3schools.com/css/css_rwd_mediaqueries.asp
So if the screen resolution is not at least 900px that icon is going to disappear, you can do the same which each icon and just leave one single icon for small screens that could simply display a vertical menu.

**Comment by ferbaco86** [comment]
Thanks Isaac!

**Comment by HADDADSOHAIB** [comment]
Thanks for your remarks, we added media queries in the latest merge.
